<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE wiperdog [
	<!ELEMENT wiperdog (welcome,appName,appVersion,runAppStr, readmePath, licensePath, installAsOSService, installLogPath, installMode)>
	<!ELEMENT welcome (paragraph)*>
	<!ELEMENT paragraph (#PCDATA)>
	<!ELEMENT appName (name)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT appVersion (number)>
	<!ELEMENT number (#PCDATA)>
	<!ELEMENT runAppStr (str)>
	<!ELEMENT str (#PCDATA)>
	<!ELEMENT readmePath (path)>
	<!ELEMENT path (#PCDATA)>
	<!ELEMENT licensePath (path)>
	<!ELEMENT installAsOSService (str)>
	<!ELEMENT installLogPath (path)>
	<!ELEMENT installMode (str)>
]>
<wiperdog>
	<welcome>
		<paragraph/>		
		<paragraph>Wiperdog is multi purpose monitoring DBMS system writing in Groovy.</paragraph>
		<paragraph>Wiperdog has some major components as followings:</paragraph>
		<paragraph>1. MongoDB is used as a storage DBMS for storing monitoring result data.</paragraph>
		<paragraph>Mongodb is good for large scale system with high concurrence access, it also provide a very good performance</paragraph>
		<paragraph>2. XWiki is used as a front-end user GUI. It is easy customizable and configurable </paragraph>
		<paragraph>3. Groovy monitoring framework, has built by Insight-tech, is well-structure, easy for maintenance, scalable and configurable</paragraph>
		<paragraph>Thank you for using wiperdog, please follow screen construction to continue the installation</paragraph>		
	</welcome>
	<appName>
		<name>Wiperdog multi purposes monitoring system</name>
	</appName>
	<appVersion>
		<number>1.0.1</number>
	</appVersion>	
	<runAppStr><str>java -classpath lib/java/bundle.a/groovy-all-2.2.1.jar groovy.ui.GroovyMain installer/installer.groovy</str></runAppStr>
	<!-- runAppStr><str>java -classpath lib/java/bundle.a/groovy-all-2.2.1.jar -Djava.util.logging.config.file=etc/logging.properties groovy.ui.GroovyMain installer/installer.groovy</str></runAppStr-->
	<readmePath><path>readme.txt</path></readmePath>
	<licensePath><path>license.txt</path></licensePath>	
	<installAsOSService><str>yes</str></installAsOSService>
	<!-- INSTALLER_LOG_PATH will be replaced while running, based on current directory which contain installer jar file-->
	<installLogPath><path>INSTALLER_LOG_PATH</path></installLogPath>
	<!-- INSTALL_MODE will be replaced while running, based on -d option in the main installer-->
	<installMode><str>INSTALL_MODE</str></installMode>
</wiperdog>
