=== wiperdog/wiperdog/org.wiperdog.jobmanager/paxtest/jd2.dtd
<!ELEMENT JobDefinition (Job | Trigger | AssignTrigger | JobNet | JobClass | AssignJobClass)*>
<!ELEMENT Job (Arg*)>
<!ATTLIST Job name CDATA #REQUIRED>
<!ATTLIST Job scriptPath CDATA #IMPLIED>
<!ATTLIST Job javaClass CDATA #IMPLIED>
<!ATTLIST Job javaMethod CDATA #IMPLIED>
<!ATTLIST Job osgiService CDATA #IMPLIED>
<!ATTLIST Job interrupted CDATA #IMPLIED>
<!ATTLIST Job misfired CDATA #IMPLIED>
<!ATTLIST Job maxRunTime CDATA #IMPLIED>
<!ATTLIST Job stdout CDATA #IMPLIED>
<!ATTLIST Job stderr CDATA #IMPLIED>
<!ELEMENT Arg (#PCDATA)>
<!ELEMENT Trigger EMPTY>
<!ATTLIST Trigger name CDATA #REQUIRED>
<!ATTLIST Trigger at CDATA #REQUIRED>
<!ATTLIST Trigger forJobName CDATA #IMPLIED>
<!ELEMENT AssignTrigger EMPTY>
<!ATTLIST AssignTrigger trigger CDATA #REQUIRED>
<!ATTLIST AssignTrigger job CDATA #REQUIRED>
<!ELEMENT JobNet (Terminal | Operator | Pseudo)*>
<!ATTLIST JobNet name CDATA #REQUIRED>
<!ATTLIST JobNet enabled (true | false) #IMPLIED>
<!ELEMENT Terminal (Predecessors)*>
<!ATTLIST Terminal type (force | prohibit) #REQUIRED>
<!ATTLIST Terminal forJobName CDATA #REQUIRED>
<!ATTLIST Terminal delay CDATA #IMPLIED>
<!ELEMENT Operator (Predecessors)*>
<!ATTLIST Operator type CDATA #REQUIRED>
<!ATTLIST Operator name CDATA #IMPLIED>
<!ATTLIST Operator count CDATA #IMPLIED>
<!ELEMENT Predecessor EMPTY>
<!ATTLIST Predecessor name CDATA #REQUIRED>
<!ELEMENT Predecessors (Predecessor | Operator | Pseudo)*>
<!ELEMENT Pseudo EMPTY>
<!ATTLIST Pseudo name CDATA #REQUIRED>
<!ELEMENT JobClass (MemberJob*)>
<!ATTLIST JobClass name CDATA #IMPLIED>
<!ATTLIST JobClass concurrency CDATA #IMPLIED>
<!ATTLIST JobClass maxruntime CDATA #IMPLIED>
<!ATTLIST JobClass maxwaittime CDATA #IMPLIED>
<!ELEMENT AssignJobClass EMPTY>
<!ATTLIST AssignJobClass forJobName CDATA #REQUIRED>
<!ATTLIST AssignJobClass class CDATA #REQUIRED>
<!ELEMENT MemberJob EMPTY>
<!ATTLIST MemberJob name CDATA #REQUIRED>

=== wiperdog/wiperdog/org.wiperdog.jobmanager/paxtest/dstest5.xml
<?xml version="1.0"?>
<!DOCTYPE JobDefinition SYSTEM "jd2.dtd">
<JobDefinition>
  <Job name="job1" scriptPath="job1.sh"/>
  <Job name="job2" scriptPath="job2.sh"/>
  <Job name="job3" scriptPath="job3.sh"/>
  <Job name="job4" scriptPath="job4.sh"/>
  <Trigger name="trigger1" forJobName="job1" at="2000"/>
  <Trigger name="trigger2" forJobName="job2" at="3000"/>
  <Trigger name="trigger3" forJobName="job3" at="4000"/>
  <!-- <Trigger name="trigger4" forJobName="job4" at="5000"/> -->
  <JobNet name="net1" enabled="true">
   <Terminal type="force" forJobName="job4">
    	<Predecessors>
    		<!-- 先行要素 "and2" へのリファレンス -->
	      <Predecessor name="or3"/>
		</Predecessors>
    </Terminal>
  	<Operator type="or" name="or3">
  		<Predecessors>
  			<Predecessor name="and2"/>
  			<Predecessor name="job3"/>
  		</Predecessors>
  	</Operator>
  	<Operator type="and" name="and2">
  		<Predecessors>
	  		<Predecessor name="job1"/>
	  		<Predecessor name="job2"/>
  		</Predecessors>
  	</Operator>
    <!-- "and1" ANDオペレータ -->
  </JobNet>
  <JobNet name="net2" enabled="true">
  	<Terminal type="force" forJobName="job4" delay="5000">
  		<Predecessors>
  			<Predecessor name="not1"/>
  		</Predecessors>
  	</Terminal>
  	<Operator type="not" name="not1">
  		<Predecessors>
  			<Predecessor name="job4"/>
  		</Predecessors>
  	</Operator>
  </JobNet>
</JobDefinition>

=== wiperdog/wiperdog/org.wiperdog.jobmanager/paxtest/dstest7.xml
<?xml version="1.0"?>
<!DOCTYPE JobDefinition SYSTEM "jd2.dtd">
<JobDefinition>
  <Job name="job4" scriptPath="job4.sh"/>
  <Job name="job5" scriptPath="job5.sh"/>
  <Trigger name="trigger4" forJobName="job4" at="*/2 * * * * ?"/>
  <JobNet name="net2" enabled="true">
  	<Terminal type="force" forJobName="job5" delay="5000">
  		<Predecessors>
  			<Predecessor name="count1"/>
  		</Predecessors>
  	</Terminal>
  	<Operator type="not" name="not1">
  		<Predecessors>
  			<Predecessor name="job4"/>
  		</Predecessors>
  	</Operator>
  	<Operator type="count" name="count1" count="5">
  		<Predecessors>
  			<Predecessor name="not1"/>
  		</Predecessors>
  	</Operator>
  </JobNet>
</JobDefinition>

=== wiperdog/wiperdog/org.wiperdog.jobmanager/paxtest/dstest9.xml
<?xml version="1.0"?>
<!DOCTYPE JobDefinition SYSTEM "jd2.dtd">
<JobDefinition>
  <Job name="job9" scriptPath="job9.sh" stdout="stdout:.*ERROR.*"/>
  <Trigger name="trigger1" forJobName="job9" at="1000"/>
  <Job name="notifyjob1" scriptPath="notify1.sh">
    <Arg>execution of job9 was succeeded</Arg>
  </Job>
  <Job name="notifyjob2" scriptPath="notify1.sh">
    <Arg>pattern matched(ERROR)</Arg>
  </Job>
  <JobNet name="net1">
  	<Operator type="or" name="or1">
  		<Predecessors>
	  		<Predecessor name="job9"/>
  		</Predecessors>
  	</Operator>
  	<Operator type="or" name="or2">
  		<Predecessors>
  			<Predecessor name="job9_OUTPATTERN"/>
  		</Predecessors>
  	</Operator>
   <Terminal type="force" forJobName="notifyjob1">
    	<Predecessors>
	      <Predecessor name="or1"/>
		</Predecessors>
    </Terminal>
   <Terminal type="force" forJobName="notifyjob2">
    	<Predecessors>
	      <Predecessor name="or2"/>
		</Predecessors>
    </Terminal>
  </JobNet>
</JobDefinition>

=== wiperdog/wiperdog/org.wiperdog.jobmanager/paxtest/dstest8.xml
<?xml version="1.0"?>
<!DOCTYPE JobDefinition SYSTEM "jd2.dtd">
<JobDefinition>
  <Job name="job8" scriptPath="job8.sh" maxRunTime="3000" interrupted="interrupted"/>
  <Trigger name="trigger1" forJobName="job8" at="1000"/>
  <Job name="notifyjob1" scriptPath="notify1.sh">
    <Arg>1</Arg>
  </Job>
  <Job name="notifyjob2" scriptPath="notify1.sh">
    <Arg>2</Arg>
  </Job>
  <JobNet name="net1">
  	<Operator type="or" name="or1">
  		<Predecessors>
	  		<Predecessor name="job8"/>
  		</Predecessors>
  	</Operator>
  	<Operator type="or" name="or2">
  		<Predecessors>
  			<Predecessor name="job8_INTERRUPTED"/>
  		</Predecessors>
  	</Operator>
   <Terminal type="force" forJobName="notifyjob1">
    	<Predecessors>
	      <Predecessor name="or1"/>
		</Predecessors>
    </Terminal>
   <Terminal type="force" forJobName="notifyjob2">
    	<Predecessors>
	      <Predecessor name="or2"/>
		</Predecessors>
    </Terminal>
  </JobNet>
</JobDefinition>

=== wiperdog/wiperdog/org.wiperdog.jobmanager/paxtest/jdsample1.xml
<?xml version="1.0"?>
<!DOCTYPE JobDefinition SYSTEM "jd2.dtd">
<JobDefinition>
  <!-- "job1" コマンド"command1"を起動するジョブ -->
  <Job name="job1" scriptPath="/home/insight/bin/command1">
    <Arg>arg1</Arg>
    <Arg>arg2</Arg>
  </Job>
  <!-- "job2" コマンド"command2"を起動するジョブ -->
  <Job name="job2" scriptPath="/path/to/command2"/>
  <!-- "job3" スタティックメソッド 'SampleJob.exec("test")' を起動するメソッド -->
  <Job name="job3" javaClass="com.insight_tec.pi.sample.SampleJob" javaMethod="exec">
  	<Arg>test</Arg>
  </Job>
  <!-- "Job4" OSGiサービス "SampleService"のexecメソッドを実行するジョブ -->
  <Job name="Job4" osgiService="objectclass='com.insight_tec.pi.sample.SampleService'" javaMethod="exec"/>
  <!-- "Job5" コマンド"command5"を実行するジョブ -->
  <Job name="Job5" scriptPath="/path/to/command5"/>
  <!-- "trigger1" 毎分0秒にジョブ("Job1")をキックするトリガ -->
  <Trigger forJobName="job1" name="trigger1" at="0 * * * * ?"/>
  <!--  "trigger2" 全定義が読まれたあと即座にジョブをキックするトリガ -->
  <Trigger name="trigger2" at="now"/>
  <!-- "trigger2" を "job2"に割り当て -->
  <AssignTrigger trigger="trigger2" job="job2"/>
  <!-- ジョブネット"jobnet1" -->
  <JobNet name="jobnet1" enabled="true">
  	<!-- "pseudo1" JobNet外部から割込みを入れるための擬似要素 -->
    <Pseudo name="pseudo1"/>
    <!-- "job3"と接続する強制実行端末要素 -->
    <Terminal type="force" forJobName="job3">
    	<Predecessors>
    		<!-- 先行要素 "and2" へのリファレンス -->
	      <Predecessor name="and2"/>
		</Predecessors>
    </Terminal>
    <!-- "and1" ANDオペレータ -->
    <Operator type="and" name="and1">
    	<Predecessors>
    		<!-- 先行要素 "job1" へのリファレンス -->
	      <Predecessor name="job1"/>
	      <!-- 先行要素 "job2"へのリファレンス -->
	      <Predecessor name="job2"/>
      </Predecessors>
    </Operator>
    <!-- "or1" OR オペレータ -->
    <Operator type="or" name="or1">
    	<Predecessors>
    		<!-- 先行ジョブ"job4"へのリファレンス -->
	      <Predecessor name="job4"/>
	      <!-- 先行ジョブ"job5"へのリファレンス -->
	      <Predecessor name="job5"/>
	      <!-- 先行ジョブ"pseudo1"へのリファレンス -->
	      <Predecessor name="pseudo1"/>
      	</Predecessors>
    </Operator>
    <!-- "And2" Andオペレータ -->
    <Operator type="and" name="and2">
    	<Predecessors>
    		<!-- 先行要素 "and1"へのリファレンス -->
	      <Predecessor name="and1"/>
	      <!-- 先行要素"or1"へのリファレンス -->
	      <Predecessor name="or1"/>
		</Predecessors>
    </Operator>
  </JobNet>
  <!-- ジョブネット"jobnet2" -->
  <JobNet name="jobnet2" enabled="true">
  	<!-- "pseudo1" ジョブネット外部から割込みを入れるための擬似要素 -->
    <Pseudo name="pseudo1"/>
    <!-- "job3"と接続する強制実行端末要素、10秒ディレイ付き -->
    <Terminal type="force" forJobName="job3" delay="10000">
    	<Predecessors>
    		<!-- 先行要素 "counter1" へのリファレンス -->
	      <Predecessor name="counter1"/>
      	</Predecessors>
    </Terminal>
    <!-- "counter1" カウンタオペレータ要素、カウント数=10 -->
    <Operator type="counter" name="counter1" count="10">
    	<Predecessors>
    		<!-- 先行要素"not1"へのリファレンス -->
	      <Predecessor name="not1"/>
      <!-- <Predecessor name="pseudo1" option="position=1"/> -->
      </Predecessors>
    </Operator>
    <!-- "not1" NOTオペレータ要素 -->
    <Operator type="not" name="not1">
    	<Predecessors>
    		<!-- 先行要素"job3"へのリファレンス -->
      		<Predecessor name="job3"/>
		</Predecessors>
    </Operator>
  </JobNet>
  <!-- "class1" ジョブクラス 同時実行数=1 -->
  <JobClass name="class1" concurrency="1" maxruntime="" maxwaittime=""/>
  <!-- ジョブ "job1" をジョブクラス "class1"へ割当 -->
  <AssignJobClass forJobName="job1" class="class1"/>
  <!-- ジョブ "job2" をジョブクラス "class1"へ割当 -->
  <AssignJobClass forJobName="job2" class="class1"/>
  <!-- ジョブ "job3" をジョブクラス "class1"へ割当 -->
  <AssignJobClass forJobName="job3" class="class1"/>
  
</JobDefinition>

=== wiperdog/wiperdog/org.wiperdog.jobmanager/paxtest/jdsample2.xml
<?xml version="1.0"?>
<!DOCTYPE JobDefinition SYSTEM "jd2.dtd">
<JobDefinition>
  <Job name="job1" scriptPath="/path/to/command1">
    <Arg>arg1</Arg>
    <Arg>arg2</Arg>
  </Job>
  <Job name="job2" scriptPath="/path/to/command2"/>
  <Job name="job3" javaClass="com.insight_tec.pi.sample.SampleJob" javaMethod="exec">
  	<Arg>test</Arg>
  </Job>
  <Job name="Job4" osgiService="objectclass='com.insight_tec.pi.sample.SampleService'"/>
  <Job name="Job5" scriptPath="/path/to/command5"/>
  <Trigger forJobName="job1" name="trigger1" at="0 * * * * ?"/>
  <Trigger name="trigger2" at="now"/>
  <AssignTrigger trigger="trigger2" job="job2"/>
  <JobNet name="one" enabled="true">
    <Pseudo name="pseudo1"/>
    <Terminal type="force" forJobName="job3">
    	<Predecessors>
	      <Predecessor name="and2"/>
	      <Operator type="and">
	      	<Predecessors>
		        <Predecessor name="job1"/>
		        <Predecessor name="job2"/>
		        <Operator type="or">
		        	<Predecessors>
			          <Predecessor name="job4"/>
			          <Predecessor name="job5"/>
			          <Predecessor name="pseudo1"/>
					</Predecessors>
		        </Operator>
	        </Predecessors>
	      </Operator>
      </Predecessors>
    </Terminal>
  </JobNet>
  <JobNet name="two" enabled="true">
    <Pseudo name="pseudo1"/>
    <Terminal type="force" forJobName="job3" delay="10sec">
    	<Predecessors>
	      <Predecessor name="counter1"/>
	      <Operator type="counter" count="10">
	      	<Predecessors>
	        <Operator type="not">
	        	<Predecessors>
	          	<Predecessor name="job3"/>
	          </Predecessors>
	        </Operator>
	        </Predecessors>
	      </Operator>
      	</Predecessors>
    </Terminal>
  </JobNet>
  <JobClass concurrency="2" maxruntime="10min" maxwaittime="10min">
    <MemberJob name="job1"/>
    <MemberJob name="job2"/>
    <MemberJob name="job3"/>
    
  </JobClass>
  
</JobDefinition>

=== wiperdog/wiperdog/org.wiperdog.jobmanager/paxtest/dstest6.xml
<?xml version="1.0"?>
<!DOCTYPE JobDefinition SYSTEM "jd2.dtd">
<JobDefinition>
  <Job name="job4" scriptPath="job4.sh"/>
  <Trigger name="trigger4" forJobName="job4" at="5000"/>
  <JobNet name="net2" enabled="true">
  	<Terminal type="force" forJobName="job4" delay="5000">
  		<Predecessors>
  			<Predecessor name="not1"/>
  		</Predecessors>
  	</Terminal>
  	<Operator type="not" name="not1">
  		<Predecessors>
  			<Predecessor name="job4"/>
  		</Predecessors>
  	</Operator>
  </JobNet>
</JobDefinition>
